---
- name: julia dep pkgs
  package: name={{item}} state=latest
  with_items:
    - git
    - curl
    - wget
    - tar
    
- name: download julia
  get_url: >
    url={{julia_tgz_url}}
    dest=/tmp/{{julia_tgz}}
    owner=root
    group=root
    mode=644

- name: unarchive/install julia
  command: tar --strip-components=1 -zxvf /tmp/{{julia_tgz}} -C {{julia_prefix}}
  args:
    creates: '{{julia_prefix}}/bin/julia'

