---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ansible_distribution_release}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: julia dep pkgs
  become: yes
  become_user: root
  package: name={{item}} state=present
  with_items: '{{julia_dep_pkgs}}'
    
- name: download julia
  become: yes
  become_user: root
  get_url: >
    url={{julia_archive_url}}
    dest=/tmp/{{julia_archive}}
    mode=0644

- name: unarchive/install julia
  when: julia_archive_fmt == 'tgz'
  include: tgz.yml

- name: unzip/install julia
  when: julia_archive_fmt == 'zip'
  include: zip.yml

