---
- name: unarchive/install julia
  command: tar --strip-components=1 -zxvf /tmp/{{julia_archive}} -C {{julia_prefix}}
  args:
    creates: '{{julia_prefix}}/bin/julia'

- name: cleanup
  when: julia_install_cleanup == True
  file: >
    name={{item}} state=absent
  with_items:
    - "/tmp/{{julia_archive}}"
